// Date: 21-04-2014 14:31:52
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package assets.FactoryCraft.models;
import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelMotor extends ModelBase
{
  //fields
    ModelRenderer MotorBase;
    ModelRenderer MoterkapselsideU;
    ModelRenderer MoterkapselsideD;
    ModelRenderer MoterkapselsideR;
    ModelRenderer MoterkapselsideL;
  
  public ModelMotor()
  {
    textureWidth = 128;
    textureHeight = 32;
    
      MotorBase = new ModelRenderer(this, 0, 0);
      MotorBase.addBox(0F, 0F, 0F, 10, 10, 9);
      MotorBase.setRotationPoint(-5F, 14F, -2F);
      MotorBase.setTextureSize(128, 32);
      MotorBase.mirror = true;
      setRotation(MotorBase, 0F, 0F, 0F);
      MoterkapselsideU = new ModelRenderer(this, 60, 0);
      MoterkapselsideU.addBox(0F, 0F, 0F, 4, 1, 7);
      MoterkapselsideU.setRotationPoint(-2F, 16F, -6F);
      MoterkapselsideU.setTextureSize(128, 32);
      MoterkapselsideU.mirror = true;
      setRotation(MoterkapselsideU, 0F, 0F, 0F);
      MoterkapselsideD = new ModelRenderer(this, 40, 0);
      MoterkapselsideD.addBox(0F, 0F, 0F, 1, 4, 7);
      MoterkapselsideD.setRotationPoint(2F, 17F, -6F);
      MoterkapselsideD.setTextureSize(128, 32);
      MoterkapselsideD.mirror = true;
      setRotation(MoterkapselsideD, 0F, 0F, 0F);
      MoterkapselsideR = new ModelRenderer(this, 60, 0);
      MoterkapselsideR.addBox(0F, 0F, 0F, 4, 1, 7);
      MoterkapselsideR.setRotationPoint(-2F, 21F, -6F);
      MoterkapselsideR.setTextureSize(128, 32);
      MoterkapselsideR.mirror = true;
      setRotation(MoterkapselsideR, 0F, 0F, 0F);
      MoterkapselsideL = new ModelRenderer(this, 40, 0);
      MoterkapselsideL.addBox(0F, 0F, 0F, 1, 4, 7);
      MoterkapselsideL.setRotationPoint(-3F, 17F, -6F);
      MoterkapselsideL.setTextureSize(128, 32);
      MoterkapselsideL.mirror = true;
      setRotation(MoterkapselsideL, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    MotorBase.render(f5);
    MoterkapselsideU.render(f5);
    MoterkapselsideD.render(f5);
    MoterkapselsideR.render(f5);
    MoterkapselsideL.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    //super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
