// Date: 18-04-2014 18:20:48
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package assets.FactoryCraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelChimney extends ModelBase {
	// fields
	ModelRenderer fladeF;
	ModelRenderer fladeR;
	ModelRenderer fladeL;
	ModelRenderer fladeB;
	ModelRenderer streg1;
	ModelRenderer streg2;
	ModelRenderer streg3;
	ModelRenderer streg4;
	ModelRenderer streg5;
	ModelRenderer streg6;
	ModelRenderer streg7;
	ModelRenderer streg8;
	ModelRenderer Shape9;
	ModelRenderer streg10;
	ModelRenderer streg11;
	ModelRenderer streg12;
	
	public ModelChimney() {
		textureWidth = 64;
		textureHeight = 32;
		
		fladeF = new ModelRenderer(this, 0, 0);
		fladeF.addBox(0F, 0F, 0F, 6, 16, 1);
		fladeF.setRotationPoint(-3F, 8F, -7F);
		fladeF.setTextureSize(64, 32);
		fladeF.mirror = true;
		setRotation(fladeF, 0F, 0F, 0F);
		fladeR = new ModelRenderer(this, 0, 0);
		fladeR.addBox(0F, 0F, 0F, 1, 16, 6);
		fladeR.setRotationPoint(-7F, 8F, -3F);
		fladeR.setTextureSize(64, 32);
		fladeR.mirror = true;
		setRotation(fladeR, 0F, 0F, 0F);
		fladeL = new ModelRenderer(this, 0, 0);
		fladeL.addBox(0F, 0F, 0F, 1, 16, 6);
		fladeL.setRotationPoint(6F, 8F, -3F);
		fladeL.setTextureSize(64, 32);
		fladeL.mirror = true;
		setRotation(fladeL, 0F, 0F, 0F);
		fladeB = new ModelRenderer(this, 0, 0);
		fladeB.addBox(0F, 0F, 0F, 6, 16, 1);
		fladeB.setRotationPoint(-3F, 8F, 6F);
		fladeB.setTextureSize(64, 32);
		fladeB.mirror = true;
		setRotation(fladeB, 0F, 0F, 0F);
		streg1 = new ModelRenderer(this, 0, 0);
		streg1.addBox(0F, 0F, 0F, 1, 16, 1);
		streg1.setRotationPoint(-6F, 8F, 3F);
		streg1.setTextureSize(64, 32);
		streg1.mirror = true;
		setRotation(streg1, 0F, 0F, 0F);
		streg2 = new ModelRenderer(this, 0, 0);
		streg2.addBox(0F, 0F, 0F, 1, 16, 1);
		streg2.setRotationPoint(-6F, 8F, -4F);
		streg2.setTextureSize(64, 32);
		streg2.mirror = true;
		setRotation(streg2, 0F, 0F, 0F);
		streg3 = new ModelRenderer(this, 0, 0);
		streg3.addBox(0F, 0F, 0F, 1, 16, 1);
		streg3.setRotationPoint(4F, 8F, -5F);
		streg3.setTextureSize(64, 32);
		streg3.mirror = true;
		setRotation(streg3, 0F, 0F, 0F);
		streg4 = new ModelRenderer(this, 0, 0);
		streg4.addBox(0F, 0F, 0F, 1, 16, 1);
		streg4.setRotationPoint(5F, 8F, -4F);
		streg4.setTextureSize(64, 32);
		streg4.mirror = true;
		setRotation(streg4, 0F, 0F, 0F);
		streg5 = new ModelRenderer(this, 0, 0);
		streg5.addBox(0F, 0F, 0F, 1, 16, 1);
		streg5.setRotationPoint(5F, 8F, 3F);
		streg5.setTextureSize(64, 32);
		streg5.mirror = true;
		setRotation(streg5, 0F, 0F, 0F);
		streg6 = new ModelRenderer(this, 0, 0);
		streg6.addBox(0F, 0F, 0F, 1, 16, 1);
		streg6.setRotationPoint(-5F, 8F, 4F);
		streg6.setTextureSize(64, 32);
		streg6.mirror = true;
		setRotation(streg6, 0F, 0F, 0F);
		streg7 = new ModelRenderer(this, 0, 0);
		streg7.addBox(0F, 0F, 0F, 1, 16, 1);
		streg7.setRotationPoint(3F, 8F, 5F);
		streg7.setTextureSize(64, 32);
		streg7.mirror = true;
		setRotation(streg7, 0F, 0F, 0F);
		streg8 = new ModelRenderer(this, 0, 0);
		streg8.addBox(0F, 0F, 0F, 1, 16, 1);
		streg8.setRotationPoint(-4F, 8F, 5F);
		streg8.setTextureSize(64, 32);
		streg8.mirror = true;
		setRotation(streg8, 0F, 0F, 0F);
		Shape9 = new ModelRenderer(this, 0, 0);
		Shape9.addBox(0F, 0F, 0F, 1, 16, 1);
		Shape9.setRotationPoint(4F, 8F, 4F);
		Shape9.setTextureSize(64, 32);
		Shape9.mirror = true;
		setRotation(Shape9, 0F, 0F, 0F);
		streg10 = new ModelRenderer(this, 0, 0);
		streg10.addBox(0F, 0F, 0F, 1, 16, 1);
		streg10.setRotationPoint(-5F, 8F, -5F);
		streg10.setTextureSize(64, 32);
		streg10.mirror = true;
		setRotation(streg10, 0F, 0F, 0F);
		streg11 = new ModelRenderer(this, 0, 0);
		streg11.addBox(0F, 0F, 0F, 1, 16, 1);
		streg11.setRotationPoint(3F, 8F, -6F);
		streg11.setTextureSize(64, 32);
		streg11.mirror = true;
		setRotation(streg11, 0F, 0F, 0F);
		streg12 = new ModelRenderer(this, 0, 0);
		streg12.addBox(0F, 0F, 0F, 1, 16, 1);
		streg12.setRotationPoint(-4F, 8F, -6F);
		streg12.setTextureSize(64, 32);
		streg12.mirror = true;
		setRotation(streg12, 0F, 0F, 0F);
	}
	
	/*public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5);
		fladeF.render(f5);
		fladeR.render(f5);
		fladeL.render(f5);
		fladeB.render(f5);
		streg1.render(f5);
		streg2.render(f5);
		streg3.render(f5);
		streg4.render(f5);
		streg5.render(f5);
		streg6.render(f5);
		streg7.render(f5);
		streg8.render(f5);
		Shape9.render(f5);
		streg10.render(f5);
		streg11.render(f5);
		streg12.render(f5);
	}*/
	
	public void renderAll() {
		fladeF.render(0.0625F);
		fladeR.render(0.0625F);
		fladeL.render(0.0625F);
		fladeB.render(0.0625F);
		streg1.render(0.0625F);
		streg2.render(0.0625F);
		streg3.render(0.0625F);
		streg4.render(0.0625F);
		streg5.render(0.0625F);
		streg6.render(0.0625F);
		streg7.render(0.0625F);
		streg8.render(0.0625F);
		Shape9.render(0.0625F);
		streg10.render(0.0625F);
		streg11.render(0.0625F);
		streg12.render(0.0625F);
	}
	
	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
	
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
		// super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}
	
}
