// Date: 01-05-2014 19:36:24
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.FactoryCraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelSolarPanel extends ModelBase
{
  //fields
    ModelRenderer SolarPanel;
    ModelRenderer LegL;
    ModelRenderer LegR;
    ModelRenderer SolarPanelPart;
    ModelRenderer Wire;
    ModelRenderer BendWire;
    ModelRenderer WireHolder;
  
  public ModelSolarPanel()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      SolarPanel = new ModelRenderer(this, 34, 0);
      SolarPanel.addBox(-7F, 0F, 0F, 14, 17, 1);
      SolarPanel.setRotationPoint(0F, 15F, 6F);
      SolarPanel.setTextureSize(64, 32);
      SolarPanel.mirror = true;
      setRotation(SolarPanel, -1F, 0F, 0F);
      LegL = new ModelRenderer(this, 0, 0);
      LegL.addBox(0F, 0F, 0F, 1, 8, 1);
      LegL.setRotationPoint(6F, 16F, 5F);
      LegL.setTextureSize(64, 32);
      LegL.mirror = true;
      setRotation(LegL, 0F, 0F, 0F);
      LegR = new ModelRenderer(this, 0, 0);
      LegR.addBox(0F, 0F, 0F, 1, 8, 1);
      LegR.setRotationPoint(-7F, 16F, 5F);
      LegR.setTextureSize(64, 32);
      LegR.mirror = true;
      setRotation(LegR, 0F, 0F, 0F);
      SolarPanelPart = new ModelRenderer(this, 0, 0);
      SolarPanelPart.addBox(0F, 0F, 0F, 14, 1, 1);
      SolarPanelPart.setRotationPoint(-7F, 15F, 5F);
      SolarPanelPart.setTextureSize(64, 32);
      SolarPanelPart.mirror = true;
      setRotation(SolarPanelPart, -1F, 0F, 0F);
      Wire = new ModelRenderer(this, 2, 11);
      Wire.addBox(0F, 0F, 0F, 2, 2, 8);
      Wire.setRotationPoint(-1F, 19.4F, 0.5F);
      Wire.setTextureSize(64, 32);
      Wire.mirror = true;
      setRotation(Wire, 0F, 0F, 0F);
      BendWire = new ModelRenderer(this, 9, 17);
      BendWire.addBox(-1F, 0F, -1F, 2, 2, 2);
      BendWire.setRotationPoint(0F, 19.2F, 0F);
      BendWire.setTextureSize(64, 32);
      BendWire.mirror = true;
      setRotation(BendWire, 7F, 0F, 0F);
      WireHolder = new ModelRenderer(this, 52, 0);
      WireHolder.addBox(0F, 0F, 0F, 2, 3, 1);
      WireHolder.setRotationPoint(-1F, 21F, 5F);
      WireHolder.setTextureSize(64, 32);
      WireHolder.mirror = true;
      setRotation(WireHolder, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    SolarPanel.render(f5);
    LegL.render(f5);
    LegR.render(f5);
    SolarPanelPart.render(f5);
    Wire.render(f5);
    BendWire.render(f5);
    WireHolder.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    //super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
