// Date: 01-05-2014 15:24:51
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.FactoryCraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelScrewdriver extends ModelBase
{
  //fields
    ModelRenderer Hoved1;
    ModelRenderer Hoved2;
    ModelRenderer Axel1;
    ModelRenderer Overste;
    ModelRenderer Grip;
    ModelRenderer Axel2;
  
  public ModelScrewdriver()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Hoved1 = new ModelRenderer(this, 0, 0);
      Hoved1.addBox(0F, 0F, 0F, 3, 5, 1);
      Hoved1.setRotationPoint(0F, 1F, 0F);
      Hoved1.setTextureSize(64, 32);
      Hoved1.mirror = true;
      setRotation(Hoved1, 0F, 0F, 0F);
      Hoved2 = new ModelRenderer(this, 0, 0);
      Hoved2.addBox(0F, 0F, 0F, 1, 5, 3);
      Hoved2.setRotationPoint(1F, 1F, -1F);
      Hoved2.setTextureSize(64, 32);
      Hoved2.mirror = true;
      setRotation(Hoved2, 0F, 0F, 0F);
      Axel1 = new ModelRenderer(this, 29, 0);
      Axel1.addBox(0F, 0F, 0F, 3, 6, 3);
      Axel1.setRotationPoint(0F, 4F, -1F);
      Axel1.setTextureSize(64, 32);
      Axel1.mirror = true;
      setRotation(Axel1, 0F, 0F, 0F);
      Overste = new ModelRenderer(this, 0, 0);
      Overste.addBox(0F, 0F, 0F, 1, 1, 1);
      Overste.setRotationPoint(1F, 0F, 0F);
      Overste.setTextureSize(64, 32);
      Overste.mirror = true;
      setRotation(Overste, 0F, 0F, 0F);
      Grip = new ModelRenderer(this, 43, 0);
      Grip.addBox(0F, 0F, 1F, 5, 10, 5);
      Grip.setRotationPoint(-1F, 10F, -3F);
      Grip.setTextureSize(64, 32);
      Grip.mirror = true;
      setRotation(Grip, 0F, 0F, 0F);
      Axel2 = new ModelRenderer(this, 0, 0);
      Axel2.addBox(0F, 0F, 0F, 3, 6, 3);
      Axel2.setRotationPoint(0F, 16F, -1F);
      Axel2.setTextureSize(64, 32);
      Axel2.mirror = true;
      setRotation(Axel2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Hoved1.render(f5);
    Hoved2.render(f5);
    Axel1.render(f5);
    Overste.render(f5);
    Grip.render(f5);
    Axel2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    //super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
