// Date: 30-04-2014 20:44:11
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package assets.FactoryCraft.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelLimeSaplingModel extends ModelBase {
	// fields
	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape4;
	ModelRenderer Shape5;
	ModelRenderer Shape6;
	ModelRenderer Shape7;
	ModelRenderer Shape8;
	ModelRenderer Shape9;
	ModelRenderer Shape10;
	ModelRenderer Shape11;
	ModelRenderer Shape12;
	ModelRenderer Shape13;
	ModelRenderer Shape14;
	
	public ModelLimeSaplingModel() {
		textureWidth = 128;
		textureHeight = 64;
		
		Shape1 = new ModelRenderer(this, 0, 0);
		Shape1.addBox(0F, 0F, 0F, 2, 13, 2);
		Shape1.setRotationPoint(-1F, 11F, -1F);
		Shape1.setTextureSize(128, 64);
		Shape1.mirror = true;
		setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new ModelRenderer(this, 0, 0);
		Shape2.addBox(0F, 0F, 0F, 6, 1, 1);
		Shape2.setRotationPoint(0F, 16F, 0F);
		Shape2.setTextureSize(128, 64);
		Shape2.mirror = true;
		setRotation(Shape2, 0F, 0.3905325F, -1F);
		Shape3 = new ModelRenderer(this, 0, 0);
		Shape3.addBox(0F, 0F, 0F, 6, 1, 1);
		Shape3.setRotationPoint(0F, 20F, 0F);
		Shape3.setTextureSize(128, 64);
		Shape3.mirror = true;
		setRotation(Shape3, 0F, 2.390532F, -0.4887574F);
		Shape4 = new ModelRenderer(this, 0, 0);
		Shape4.addBox(0F, 0F, 0F, 6, 1, 1);
		Shape4.setRotationPoint(-0.4F, 20.73333F, -0.8666667F);
		Shape4.setTextureSize(128, 64);
		Shape4.mirror = true;
		setRotation(Shape4, -2.130177F, -2.015779F, -2.733333F);
		Shape5 = new ModelRenderer(this, 0, 0);
		Shape5.addBox(0F, 0F, 0F, 6, 1, 1);
		Shape5.setRotationPoint(1F, 16F, 0F);
		Shape5.setTextureSize(128, 64);
		Shape5.mirror = true;
		setRotation(Shape5, 0F, 10.04142F, -1F);
		Shape6 = new ModelRenderer(this, 0, 0);
		Shape6.addBox(0F, 0F, 0F, 6, 1, 1);
		Shape6.setRotationPoint(0F, 17F, 0F);
		Shape6.setTextureSize(128, 64);
		Shape6.mirror = true;
		setRotation(Shape6, 0F, -0.6094675F, -0.1333333F);
		Shape7 = new ModelRenderer(this, 0, 0);
		Shape7.addBox(0F, 0F, 0F, 6, 1, 1);
		Shape7.setRotationPoint(0.1333333F, 17F, 0F);
		Shape7.setTextureSize(128, 64);
		Shape7.mirror = true;
		setRotation(Shape7, 0F, 10.83511F, 0.6666667F);
		Shape8 = new ModelRenderer(this, 0, 0);
		Shape8.addBox(0F, 0F, 0F, 6, 1, 1);
		Shape8.setRotationPoint(-1F, 15F, 1F);
		Shape8.setTextureSize(128, 64);
		Shape8.mirror = true;
		setRotation(Shape8, 0F, 7.574753F, -0.4F);
		Shape9 = new ModelRenderer(this, 36, 11);
		Shape9.addBox(0F, 0F, 0F, 11, 11, 11);
		Shape9.setRotationPoint(-5F, 11F, -6F);
		Shape9.setTextureSize(128, 64);
		Shape9.mirror = true;
		setRotation(Shape9, 0F, 0F, 0F);
		Shape10 = new ModelRenderer(this, 14, 0);
		Shape10.addBox(0F, 0F, 0F, 2, 9, 9);
		Shape10.setRotationPoint(-7F, 12F, -5F);
		Shape10.setTextureSize(128, 64);
		Shape10.mirror = true;
		setRotation(Shape10, 0F, 0F, 0F);
		Shape11 = new ModelRenderer(this, 14, 0);
		Shape11.addBox(0F, 0F, 0F, 9, 9, 2);
		Shape11.setRotationPoint(-4F, 12F, -8F);
		Shape11.setTextureSize(128, 64);
		Shape11.mirror = true;
		setRotation(Shape11, 0F, 0F, 0F);
		Shape12 = new ModelRenderer(this, 14, 0);
		Shape12.addBox(0F, 0F, 0F, 2, 9, 9);
		Shape12.setRotationPoint(6F, 12F, -5F);
		Shape12.setTextureSize(128, 64);
		Shape12.mirror = true;
		setRotation(Shape12, 0F, 0F, 0F);
		Shape13 = new ModelRenderer(this, 14, 0);
		Shape13.addBox(0F, 0F, 0F, 9, 9, 2);
		Shape13.setRotationPoint(-4F, 12F, 5F);
		Shape13.setTextureSize(128, 64);
		Shape13.mirror = true;
		setRotation(Shape13, 0F, 0F, 0F);
		Shape14 = new ModelRenderer(this, 14, 0);
		Shape14.addBox(0F, 0F, 0F, 9, 2, 9);
		Shape14.setRotationPoint(-4F, 9F, -5F);
		Shape14.setTextureSize(128, 64);
		Shape14.mirror = true;
		setRotation(Shape14, 0F, 0F, 0F);
	}
	
	/*public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5);
		Shape1.render(f5);
		Shape2.render(f5);
		Shape2.render(f5);
		Shape2.render(f5);
		Shape2.render(f5);
		Shape2.render(f5);
		Shape2.render(f5);
		Shape2.render(f5);
		Shape3.render(f5);
		Shape3.render(f5);
		Shape3.render(f5);
		Shape3.render(f5);
		Shape3.render(f5);
		Shape3.render(f5);
	}*/
	
	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
	
	/*public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5) {
		// super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}*/
	
	public void renderAll() {
		Shape1.render(0.0625F);
		Shape2.render(0.0625F);
		Shape3.render(0.0625F);
		Shape4.render(0.0625F);
		Shape5.render(0.0625F);
		Shape6.render(0.0625F);
		Shape7.render(0.0625F);
		Shape8.render(0.0625F);
		Shape9.render(0.0625F);
		Shape10.render(0.0625F);
		Shape11.render(0.0625F);
		Shape13.render(0.0625F);
		Shape14.render(0.0625F);
	}
}
